version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - LOG_LEVEL=info
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1G"
